### ISSUE TITLE
github-readme-wr-stats.vercel.app not working

### ISSUE THREAD

**Issue by ljorge705** [mengxyz/github-readme-wr-stats#2]
when i try to load my stats, the page throws this error:
`This page contains the following errors:
error on line 1 at column 1: Document is empty
Below is a rendering of the page up to the first error.`

[xd](https://github-readme-wr-stats.vercel.app/api/wr?font_color=white&profile=OwR5fMCWzYPxXGvRhOst&max=5)

it's a great project for streamers as you can insert the html to the OBS scene

Sorry for my bad english

**Comment by mengxyz** [comment]
Thank you for issue. I found issue because i fixed region url.

**Comment by mengxyz** [comment]
fixed pls check [:)](https://github-readme-wr-stats.vercel.app/api/wr?font_color=white&profile=OwR5fMCWzYPxXGvRhOst&max=5&region=na)

**Comment by ljorge705** [comment]
Now works, thanks for fix 🔥
