### ISSUE TITLE
bug score +10 kills on OBS

### ISSUE THREAD

**Issue by ljorge705** [mengxyz/github-readme-wr-stats#5]
when I get more than 10 kills the scoreboard fail

[Photo: photo](https://i.imgur.com/JqumYf4.png)

Please help :(

sorry for my bad english

**Comment by mengxyz** [comment]
yes is known issues. i will fix it couple day.

**Comment by mengxyz** [comment]
@ljorge705 try this url https://github-readme-wr-stats-dev.vercel.app/api/wr and report me

**Comment by ljorge705** [comment]
Now works
[PPPPP](https://i.imgur.com/Bc8VbzH.png)

Thanks!
